#!/bin/bash

function getgpgkey () {
    local keyVal
    keyVal=$(gpg -K |
          awk '/sec/{if (length($2) > 0) print $2}' |
          sed 's|.*/0x||' )
    echo -ne ${keyVal}
}

function getsshkey () {
    local sshKeys
    local Keys

    cd ${HOME}/.ssh/ &&
        sshKeys=$(ls *.pub |
                      cut -d. -f1 |
                      cut -d- -f1 |
                      cut -d_ -f2 |
                      sort -u) &&
        cd ${HOME}

    for key in ${sshKeys}
    do
        if [[ "${key}" != "gpg" ]]; then
            if [[ -f ${HOME}/.ssh/id_${key} ]]; then
                if [[ -z ${Keys} ]]; then
                    Keys="id_${key}"
                else
                    Keys="${Keys} id_${key}"
                fi
                [[ "${key}" == "dsa" ]] &&
                    echo "Warning: you are still using dsa keys."
            fi
        fi
    done
    echo -ne ${Keys}

}

function start_agents () {
    local keyVal
    local sshKeys

    if [[ -n "$DESKTOP_SESSION" ]]; then
        eval $(gnome-keyring-daemon --start)
        export SSH_AUTH_SOCK
    else
        if command -v keychain > /dev/null 2>&1; then
            # ID GPG Keys
            keyVal=$(getgpgkey) &&
                [[ -n ${keyVal} ]] &&
                eval "$(keychain --eval --agents gpg ${keyVal})"

            # ID SSH Keys
            sshKeys=$(getsshkey) &&
                [[ -n ${sshKeys} ]] &&
                eval "$(keychain --eval --agents ssh ${sshKeys})"
        fi
    fi
}

start_agents
