#!/bin/bash

# LESS man page colors (makes Man pages more readable).
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Emacs
export ALTERNATE_EDITOR=""
# $EDITOR opens in terminal
export EDITOR="emacsclient -t"
# GUI editor
export VISUAL="emacsclient -c -a emacs"

# Qt HiDPI Screens
# https://wiki.archlinux.org/index.php/HiDPI
# https://doc.qt.io/qt-5/highdpi.html
# [boolean] enables automatic scaling, based on the monitor's pixel density. This won't change the size of point-sized fonts, since point is a physical measurement unit. Multiple screens may get different scale factors.
export QT_AUTO_SCREEN_SCALE_FACTOR=0
# [numeric] defines a global scale factor for the whole application, including point-sized fonts.
export QT_SCALE_FACTOR=2
