#!/bin/bash

dtf () {
  git --git-dir="${DOTFILES}" --work-tree="${HOME}" "$@"
}

dtfnew () {
  git clone --bare $1 $DOTFILES
  dtf config --local status.showUntrackedFiles no
  dtf switch -c base

  echo "Please add and commit additional files"
  echo "using 'dtf add' and 'dtf commit', then run"
  echo "dtf push -u origin base"
}

dtfrestore () {
  mkdir "dotfiles_tmp"
  git clone --branch "${1}" --bare "${2}" --separate-git-dir="${DOTFILES}" dotfiles_tmp
  [[ -d dotfiles_tmp/.gitmodules ]] && cp dotfiles/.gitmodules ~/.gitmodules
  dtf config --local status.showUntrackedFiles no
  dtf checkout || echo -e 'Deal with conflicting files, then run (possibly with -f flag if you are OK with overwriting)\ndtf checkout'
}
