#!/bin/bash

# LESS man page colors (makes Man pages more readable).
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# GTAGS
export GTAGSLABEL=pygments

# ==================================================================================================
#
# XDG Base Directory
#
# ==================================================================================================
#export ANSIBLE_COLLECTIONS_PATH="${XDG_DATA_HOME}/ansible/collections"
#export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible.cfg"
#export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
#export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
#export DVDCSS_CACHE="$XDG_DATA_HOME/dvdcss"
#export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
#export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
#export PYLINTRC="$XDG_CONFIG_HOME/pylint/pylintrc"
#export SCREENDIR="${XDG_RUNTIME_DIR}/screen"
#export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
#export SPACEMACSDIR="${XDG_CONFIG_HOME}/.spacemacs"
#export WGETRC="$XDG_CONFIG_HOME/wgetrc"
