#!/bin/bash
# ==================================================================================================
#
# Build's a prompt that can be changed by
#
# ==================================================================================================
source "${HOME}/.bash.d/prompt_functions"

function loadprompt () {
    EXITSTATUS="$?"    # This Needs to be first
    PS1=""

    #Set Default Mode
    if [[ -z "$@" ]]; then
	      MODE=main
    else
	      MODE="$1"
    fi

    # set a fancy prompt (non-color, unless we know we "want" color)
    case "$TERM" in
	      xterm-color | screen-256color) color_prompt=yes;;
        *) color_prompt="";;
    esac

    # uncomment for a colored prompt, if the terminal has the capability; turned off by default to
    # not distract the user: the focus in a terminal window should be on the output of commands,
    # not on the prompt
    force_color_prompt=yes

    if [ -n "$force_color_prompt" ]; then
	      if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	          # We have color support; assume it's compliant with Ecma-48
	          # (ISO/IEC-6429). (Lack of such support 
	          # is extremely rare, and such
	          # a case would tend to support setf rather than setaf.)
	          color_prompt=yes
	      else
	          color_prompt=
	      fi
    fi

    case "$MODE" in 
	      none) 
	          # ""
	          export PROMPT_COMMAND=__prompt_command_none
	          ;; 
	      off) 
	          # $
	          export PROMPT_COMMAND=__prompt_command_off
	          ;;
        date) 
	          # [\t]\$ 
	          export PROMPT_COMMAND=__prompt_command_date 
	          ;; 
	      basic)
	          # [\u \w]\$
	          export PROMPT_COMMAND=__prompt_command_basic
	          ;; 
	      main) 
	          export PROMPT_COMMAND=__prompt_command_main # Func to gen PS1 after CMDs
	          ;;
	      amain)
	          MODE=main
	          export PROMPT_COMMAND=__prompt_command_advanced_main
	          ;;
	      full) 
	          export PROMPT_COMMAND=__prompt_command_full # Func to gen PS1 after CMDs
	          ;;
	      *)
	          export PROMPT_COMMAND=__prompt_command_main # Func to gen PS1 after CMDs
	          ;;
    esac
}

function __prompt_command_none () {
    history -a
    PS1=""
}

function __prompt_command_off () {
    history -a
    PS1=""
    if [ "$color_prompt" = yes ]; then
	      define_colors
    fi

    local JC=$(job_color)

    PS1="${JC}\\$ \[${DC}\]" 

    unset color_prompt force_color_prompt
    xterm_settings
}

function __prompt_command_date () {
    history -a
    PS1=""

    if [ "$color_prompt" = yes ]; then
	      define_colors
    fi

    local LOADTEXT=$(loadtext)
    local JC=$(job_color)

    PS1="[ ${LOADTEXT}]${JC}\\$ \[${DC}\]" 

    unset color_prompt force_color_prompt

    xterm_settings
}

function __prompt_command_basic() {
    history -a
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    local JC=$(job_color)
    local USERTEXT=$(usertext)
    local FC=$(disk_color)
    local HOSTTEXT=$(host_color)

    PS1="\n[ ${USERTEXT}${HOSTTEXT} ${FC}]${JC}\\$ \[${DC}\]" 

    xterm_settings
}

function __prompt_command_main() {
    EXITSTATUS=$?
    history -a
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    local LOADTEXT=$(loadtext)
    local JC=$(job_color)
    local USERTEXT=$(usertext)
    if [[ -n ${LAPTOP} ]]; then
	local BATTERY=$(bat_color)
    else
	local BATTERY=""
    fi
    local FC=$(disk_color)
    local SMILE=$(last_command)
    local HOSTTEXT=$(host_color)

    PS1="\n\
[ ${USERTEXT}${HOSTTEXT}${LOADTEXT}${BATTERY}${SMILE}${FC}]${JC}\\$ \[${DC}\]" 

    xterm_settings
}

function __prompt_command_advanced_main() {
    EXITSTATUS=$?
    history -a
    PS1=""

    if [ "$color_prompt" = yes ]; then
	      define_colors
    fi

    local LOADTEXT=$(loadtext)
    local JC=$(job_color)
    local USERTEXT=$(usertext)
    local DEBIAN_CHROOT=$(__debian_chroot)
    if [[ -n ${LAPTOP} ]]; then
	local BATTERY=$(bat_color)
    else
	local BATTERY=""
    fi
    local FC=$(disk_color)
    local SMILE=$(last_command)
    local HOSTTEXT=$(host_color)

    PS1="\n\
${DEBIAN_CHROOT}\
[ ${USERTEXT}${HOSTTEXT}${LOADTEXT}${BATTERY}${SMILE}${FC}]${JC}\\$ \[${DC}\]" 

    xterm_settings
    
}

function __prompt_command_full() {
    history -a
    #    EXITSTATUS=$?
    PS1=""

    if [ "$color_prompt" = yes ]; then
	      define_colors
    fi

    local LOADTEXT=$(loadtext)
    local USERTEXT=$(usertext)
    local JC=$(job_color)

    # Repositories
    # git
    #local BRANCH=$(__git_prompt)

    # subversion
    # currently disabled as I have nothing to check it with
    # local SVNBRANCH=$(__svn_branch)

    local BACKGROUND_JOBS=$(background_jobs)
    local STOPPED_JOBS=$(stopped_jobs)
    local DEBIAN_CHROOT=$(__debian_chroot)
    if [[ -n ${BATTERY} ]]; then
	      local BATTERY=$(bat_color)
    else
	      local BATTERY=""
    fi
    local FC=$(disk_color)
    local SMILE=$(last_command)
    local HOSTTEXT=$(host_color)
    local SCREEN=$(__screen)

    PS1="\n\
${DEBIAN_CHROOT} \n\
[ ${USERTEXT}${HOSTTEXT} ] \n\
[ ${LOADTEXT}${BATTERY}${SMILE}${SCREEN}${BACKGROUND_JOBS}${STOPPED_JOBS}] \n\
[ ${FC}${BRANCH}] \n\
${JC}\\$ \[${DC}\]"

    xterm_settings
}



loadprompt $@
