#!/bin/bash

# Define Normal Colors
BLACK='\[\e[0;30m\]'
RED='\[\e[0;31m\]'
GREEN='\[\e[0;32m\]'
YELLOW='\[\e[0;33m\]'
BLUE='\[\e[0;34m\]'
MAGENTA='\[\e[0;35m\]'
CYAN='\[\e[0;36m\]'
WHITE='\[\e[0;37m\]'

# Define Bold Colors
BBLACK='\[\e[1;30m\]'
BRED='\[\e[1;31m\]'
BGREEN='\[\e[1;32m\]'
BYELLOW="\[\e[1;33m\]"
BBLUE='\[\e[1;34m\]'
BMAGENTA='\[\e[1;35m\]'
BCYAN='\[\e[1;36m\]'
BWHITE='\[\e[1;37m\]'

# Background Colors
#On_Black='\e[40m' # Black 
On_Red='\e[41m' # Red 
#On_Green='\e[42m' # Green 
#On_Yellow='\e[43m' # Yellow 
#On_Blue='\e[44m' # Blue 
#On_Purple='\e[45m' # Purple 
#On_Cyan='\e[46m' # Cyan 
#On_White='\e[47m' # White

# Other
NO_COLOR='\[\e[0m\]'
ALERT=${BWHITE}${On_Red} # Bold White on red background
