#!/bin/bash

function define_colors() {

    # Define Normal Colors
    BLACK='\[\e[0;30m\]'
    RED='\[\e[0;31m\]'
    GREEN='\[\e[0;32m\]'
    YELLOW='\[\e[0;33m\]'
    BLUE='\[\e[0;34m\]'
    MAGENTA='\[\e[0;35m\]'
    CYAN='\[\e[0;36m\]'
    WHITE='\[\e[0;37m\]'
				        
    # Define Bold Colors
    BBLACK='\[\e[1;30m\]'
    BRED='\[\e[1;31m\]'
    BGREEN='\[\e[1;32m\]'
    BYELLOW='\[\e[1;33m\]'
    BBLUE='\[\e[1;34m\]'
    BMAGENTA='\[\e[1;35m\]'
    BCYAN='\[\e[1;36m\]'
    BWHITE='\[\e[1;37m\]'

    # Define DIM Colors
    DBLACK='\[\e[2;30m\]' # Black
    DRED='\[\e[2;31m\]' # Red
    DGREEN='\[\e[2;32m\]' # Green
    BYELLOW='\[\e[2;33m\]' # Yellow
    DBLUE='\[\e[2;34m\]' # Blue
    DMAGENTA='\[\e[2;35m\]' # Purple
    DCYAN='\[\e[2;36m\]' # Cyan
    DWHITE='\[\e[2;37m\]' # White
    
    # Define Italic Colors
    IBLACK='\[\e[3;30m\]' # Black
    IRED='\[\e[3;31m\]' # Red
    IGREEN='\[\e[3;32m\]' # Green
    IYELLOW='\[\e[3;33m\]' # Yellow
    IBLUE='\[\e[3;34m\]' # Blue
    IMAGENTA='\[\e[3;35m\]' # Purple
    ICYAN='\[\e[3;36m\]' # Cyan
    IWHITE='\[\e[3;37m\]' # White

    # Define Underline Colors
    UBLACK='\[\e[4;30m\]' # Black
    URED='\[\e[4;31m\]' # Red
    UGREEN='\[\e[4;32m\]' # Green
    UYELLOW='\[\e[4;33m\]' # Yellow
    UBLUE='\[\e[4;34m\]' # Blue
    UMAGENTA='\[\e[4;35m\]' # Purple
    UCYAN='\[\e[4;36m\]' # Cyan
    UWHITE='\[\e[4;37m\]' # White

    # Define Blinking (Flashing) Colors
    FBLACK='\[\e[5;30m\]' # Black
    FRED='\[\e[5;31m\]' # Red
    FGREEN='\[\e[5;32m\]' # Green
    FYELLOW='\[\e[5;33m\]' # Yellow
    FBLUE='\[\e[5;34m\]' # Blue
    FMAGENTA='\[\e[5;35m\]' # Purple
    FCYAN='\[\e[5;36m\]' # Cyan
    FWHITE='\[\e[5;37m\]' # White

    # Define Unknown Colors
#    UBLACK='\[\e[6;30m\]' # Black
#    URED='\[\e[6;31m\]' # Red
#    UGREEN='\[\e[6;32m\]' # Green
#    UYELLOW='\[\e[6;33m\]' # Yellow
#    UBLUE='\[\e[6;34m\]' # Blue
#    UMAGENTA='\[\e[6;35m\]' # Purple
#    UCYAN='\[\e[6;36m\]' # Cyan
#    UWHITE='\[\e[6;37m\]' # White
	    
    # Define Reverse Colors
    RBLACK='\[\e[7;30m\]' # Black
    RRED='\[\e[7;31m\]' # Red
    RGREEN='\[\e[7;32m\]' # Green
    RYELLOW='\[\e[7;33m\]' # Yellow
    RBLUE='\[\e[7;34m\]' # Blue
    RMAGENTA='\[\e[7;35m\]' # Purple
    RCYAN='\[\e[7;36m\]' # Cyan
    RWHITE='\[\e[7;37m\]' # White

    # Background Colors
    On_Black='\[\e[40m\]' # Black
    On_Red='\[\e[41m\]'   # Red
    On_Green='\[\e[42m\]' # Green
    On_Yellow='\[\e[43m\]' # Yellow
    On_Blue='\[\e[44m\]'   # Blue
    On_Purple='\[\e[45m\]' # Purple
    On_Cyan='\[\e[46m\]' # Cyan
    On_White='\[\e[47m\]' # White

    # Other
    NO_COLOR='\[\e[0m\]'
    ALERT=${BWHITE}${On_Red} # Bold White on red background

    # Set Default Color
    # User color
    USERTEXT="${GREEN}"
    #hostname color
    HC="${YELLOW}"
    #regular color
    RC="${WHITE}"
    #default color
    DC="${NO_COLOR}"
}
