#!/bin/bash

##### My (demuredemeanor) bashrc sub source install check script
# Uses tabstop=4; shiftwidth=4 tabs; foldmarker={{{}}};
# https://notabug.org/demure/dotfiles/
# legacy repo http://github.com/demure/dotfiles
# vim:set syntax=sh:

## NOTE: not using ',' as I want to be able to:
# $(sudo aptitude install $MISSING_PROGRAMS)

MISSING_CLI=""
MISSING_GUI=""

### CLI ### {{{
local CLI_LIST=(emacs geoiplookup weather-util fusermount exfatfsck parted rsync diff  gpg gpg2 aptitude)

for i in "${CLI_LIST[@]}"; do
	if [[ ! $(command -v ${i}) ]]; then
		MISSING_CLI+="${i} "
	fi
done
### End CLI ### }}}

### GUI ### {{{
local GUI_LIST=(synaptic gparted keepass2 gimp baobab k3b)

for i in "${GUI_LIST[@]}"; do
	if [[ ! $(command -v ${i}) ]]; then
		MISSING_GUI+="${i} "
	fi
done
### End GUI ### }}}


### Font ### {{{

### End Font ### }}}

### GAME ### {{{
local GAME_LIST=(playonlinux dosbox scummvm steam)

for i in "${GAME_LIST[@]}"; do
	if [[ ! $(command -v ${i}) ]]; then
		MISSING_GAME+="${i} "
	fi
done
### End Game ### }}}


### DEVEL ### {{{
local DEVEL_LIST=(build-essential git)

for i in "${DEVEL_LIST[@]}"; do
	if [[ ! $(command -v ${i}) ]]; then
		MISSING_DEVEL+="${i} "
	fi
done
### End DEVEL ### }}}
