#!/bin/bash

#########
#
# Build the Command Prompt
#
#########

function loadprompt () {
    EXITSTATUS="$?"    # This Needs to be first
    PS1=""

    #Set Default Mode
    if [ -z "$@" ]; then
	MODE=main
    else
	MODE="$1"
    fi

    # set a fancy prompt (non-color, unless we know we "want" color)
    case "$TERM" in
	xterm-color) color_prompt=yes;;
    esac

    # uncomment for a colored prompt, if the terminal 
    # has the capability; turned
    # off by default to not distract the user: 
    # the focus in a terminal window
    # should be on the output of commands, not on the prompt
    force_color_prompt=yes

    if [ -n "$force_color_prompt" ]; then
	if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	    # We have color support; assume it's compliant with Ecma-48
	    # (ISO/IEC-6429). (Lack of such support 
	    # is extremely rare, and such
	    # a case would tend to support setf rather than setaf.)
	    color_prompt=yes
	else
	    color_prompt=
	fi
    fi

    case "$MODE" in 
	none) 
	    # ""
	    export PROMPT_COMMAND=__prompt_command_none
	    ;; 
	off) 
	    # $
	    export PROMPT_COMMAND=__prompt_command_off
	    ;;
	date) 
	    # [\t]\$ 
	    export PROMPT_COMMAND=__prompt_command_date 
	    ;; 
	basic)
	    export PROMPT_COMMAND=__prompt_command_basic
	    ;; 
	main) 
	   export PROMPT_COMMAND=__prompt_command_main # Func to gen PS1 after CMDs
	    ;;
	full) 
	    export PROMPT_COMMAND=__prompt_command_full # Func to gen PS1 after CMDs
	    ;;
	*)
	    export PROMPT_COMMAND=__prompt_command_main # Func to gen PS1 after CMDs
	    ;;
    esac
}

function __prompt_command_none () {
    PS1=""
}

function __prompt_command_off () {
    PS1=""
    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    JC=$(job_color)

    PS1="${JC}\\$ \[${DC}\]" 

    unset color_prompt force_color_prompt


    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
}

function __prompt_command_date () {
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    LOADTEXT=$(loadtext)
    JC=$(job_color)

    PS1="[ ${LOADTEXT}]${JC}\\$ \[${DC}\]" 

    unset color_prompt force_color_prompt


    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
}

function __prompt_command_basic() {
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    JC=$(job_color)

    USERTEXT=$(usertext)

    FC=$(disk_color)
   
    HOSTTEXT=$(host_color)

    PS1="\n[ ${USERTEXT}${HOSTTEXT} ${FC}]${JC}\\$ \[${DC}\]" 

    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
    
}
function __prompt_command_main() {
    EXITSTATUS=$?
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    LOADTEXT=$(loadtext)
    JC=$(job_color)

    USERTEXT=$(usertext)

    DEBIAN_CHROOT=$(__debian_chroot)

    BATTERY=$(bat_color)
    
    FC=$(disk_color)
   
    SMILE=$(last_command)
    HOSTTEXT=$(host_color)

    PS1="\n\
[ ${USERTEXT}${HOSTTEXT}${LOADTEXT}${BATTERY}${SMILE}${FC}]${JC}\\$ \[${DC}\]" 

    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
    
}



function __prompt_command_advanced_main() {
    EXITSTATUS=$?
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    LOADTEXT=$(loadtext)
    JC=$(job_color)

    USERTEXT=$(usertext)

    DEBIAN_CHROOT=$(__debian_chroot)

    BATTERY=$(bat_color)
    
    FC=$(disk_color)
   
    SMILE=$(last_command)
    HOSTTEXT=$(host_color)

    PS1="\n\
${DEBIAN_CHROOT}\
[ ${USERTEXT}${HOSTTEXT}${LOADTEXT}${BATTERY}${SMILE}${FC}]${JC}\\$ \[${DC}\]" 

    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
    
}

function __prompt_command_full() {
    EXITSTATUS=$?
    PS1=""

    if [ "$color_prompt" = yes ]; then
	define_colors
    fi

    LOADTEXT=$(loadtext)

    USERTEXT=$(usertext)
    JC=$(job_color)

    # Repositories
    
    # git
    BRANCH=$(__git_prompt)

    # subversion
    # currently disabled as I have nothing to check it with
    # SVNBRANCH=$(__svn_branch)

    BACKGROUND_JOBS=$(background_jobs)
    STOPPED_JOBS=$(stopped_jobs)

    DEBIAN_CHROOT=$(__debian_chroot)

    BATTERY=$(bat_color)
    
    FC=$(disk_color)
   

    SMILE=$(last_command)
    HOSTTEXT=$(host_color)
    
    SCREEN=$(__screen)

    PS1="\n\
${DEBIAN_CHROOT}\
[ ${USERTEXT}${HOSTTEXT} ] \n\
[ ${LOADTEXT}${BATTERY}${SMILE}${SCREEN}${BACKGROUND_JOBS}${STOPPED_JOBS}] \n\
[ ${FC}${BRANCH}] \n\
${JC}\\$ \[${DC}\]" 

    # Options for xterm
    
    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
    
}


function usertext () {
    if [ "$color_prompt" = yes ]; then
    	# Root different color
	if [ $UID -eq 0 ]; then 
	    #root user color 
	    echo -ne "\[${RED}\]\u\[${DC}\]"
	elif [[ ${USER} != $(logname) ]]; then 
	    echo -ne "\[${BYELLOW}\]\u\[${DC}\]" # User is not login user.
	else
	    echo -ne "\[${GREEN}\]\u\[${DC}\]"
	fi
    else
	echo -ne "\u"
    fi
}

# Returns a color indicating system load. 
function loadtext() { 

    local LOAD=$(cat /proc/loadavg | awk '{print $1}')
    local CORES=$(grep 'model name' /proc/cpuinfo | wc -l)
    local LOADPER=$(echo ${LOAD} ${CORES} | awk '{print $1 / $2 * 100}' | cut -d. -f1)

    LOADCOLOR=$(loadcolor)

    if [ ${LOADPER} -gt ${HIGHUSE} ]; then
	SYMBOL=$'\u2622'
    elif [ ${LOADPER} -gt ${MEDUSE} ]; then
	SYMBOL=$'\u26a0'
    elif [ ${LOADPER} -gt ${LOWUSE} ]; then
	SYMBOL=$'\u2699'
    else
	SYMBOL=$'\u2603'
    fi
    if [ "${MODE}" = "full" ] || [ "${MODE}" = "date" ]; then
	echo -ne "\[${LOADCOLOR}\]\A ${SYMBOL} \[${DC}\]"
    else
	echo -ne "\[${LOADCOLOR}\]${SYMBOL} \[${DC}\]"
    fi
}


function background_jobs () {
    local BKGJBS=$(jobs -r | wc -l | tr -d ' ')
    if [ ${BKGJBS} -gt 2 ]; then
	echo -ne "\[${RED}\]bg:${BKGJBS}\[${DC}\] "
    elif [ ${BKGJBS} -gt 0 ]; then
	echo -ne "\[${YELLOW}\]bg:${BKGJBS}\[${DC}\] "
    fi
}

function stopped_jobs () {
    local STPJBS=$(jobs -s | wc -l | tr -d ' ')
    if [ ${STPJBS} -gt 2 ]; then
	echo -ne "\[${RED}\]stp:${STPJBS}\[${DC}\] "
    elif [ ${STPJBS} -gt 0 ]; then
	echo -ne "\[${YELLOW}\]stp:${STPJBS}\[${DC}\] "
    fi
}

# Returns a color according to running/suspended jobs. 
function job_color() { 
    if [ $(jobs -s | wc -l) -gt "0" ]; then 
	echo -en "\[${BYELLOW}\]"
    elif [ $(jobs -r | wc -l) -gt "0" ] ; then 
	echo -en "${BCYAN}" 
    elif [ $(jobs -r | wc -l) -gt "0" ] && [ $(jobs -s | wc -l) -gt "0" ]; then 
	echo -en "\[${RED}\]"
    else
	if [ $UID -eq 0 ]; then 
	    #root user color 
	    echo -ne "\[${RED}\]"
	elif [[ ${USER} != $(logname) ]]; then 
	    echo -ne "\[${BYELLOW}\]" # User is not login user.
	else
	    echo -ne "\[${GREEN}\]"
	fi
    fi 
}


#Returns a color according to free disk space in $PWD. 
function disk_color() { 
    if [ ! -w "${PWD}" ] ; then 
	echo -ne "\[${RED}\]\w \[${DC}\] " # No 'write' privilege in the current directory. 
    elif [ -s "${PWD}" ] ; then 
	local used=$(command df -P "$PWD" | awk 'END {print $5} {sub(/%/,"")}') 
	if [ ${used} -gt ${ALERTUSE} ]; then 
	    echo -ne "${ALERT}\w \[${DC}\] " # Disk almost full (>95%). 
	elif [ ${used} -gt ${HIGHUSE} ]; then 
	    echo -ne "\[${BRED}\]\w \[${DC}\] " # Free disk space almost gone. 
	else echo -ne "\[${GREEN}\]\w \[${DC}\] " # Free disk space is ok. 
	fi 
    else 
	echo -ne "\[${CYAN}\]\w \[${DC}\] " # Current directory is size '0' (like /proc, /sys etc). 
    fi 
}


# Display the branch name of git repository 
# Green -> clean 
# purple -> untracked files 
# red -> files to commit 
function __git_prompt() {   
    ### Add Git Status ### {{{
    ## Inspired by http://www.terminally-incoherent.com/blog/2013/01/14/whats-in-your-bash-prompt/
    if [[ $(command -v git) ]]; then
	local GStat="$(git status --porcelain -b 2>/dev/null | tr '\n' ':')"

	if [ "$GStat" ]; then
	    ### Fetch Time Check ### {{{
	    local LAST=$(stat -c %Y $(git rev-parse --git-dir 2>/dev/null)/FETCH_HEAD 2>/dev/null)
	    if [ "${LAST}" ]; then
		local TIME=$(echo $(date +"%s") - ${LAST} | bc)
		## Check if more than 60 minutes since last
		if [ "${TIME}" -gt "3600" ]; then
		    git fetch 2>/dev/null
		    GITSTATUSPROMPT= ' +'
		    ## Refresh var
		    local GStat="$(git status --porcelain -b 2>/dev/null | tr '\n' ':')"
		fi
	    fi
	    ### End Fetch Check ### }}}
	    
	    ### Test For Changes ### {{{
	    ## Change this to test for 'ahead' or 'behind'!
	    local GChanges="$(echo ${GStat} | tr ':' '\n' | grep -v "^$" | grep -v "^\#\#" | wc -l | tr -d ' ')"
	    if [ "$GChanges" == "0" ]; then
		local GitCol=$MAGENTA
	    else
		local GitCol=$CYAN
	    fi
	    ### End Test Changes ### }}}
	    
	    ### Find Branch ### {{{
	    local GBra="$(echo ${GStat} | tr ':' '\n' | grep "^##" | cut -c4- | grep -o "^[a-zA-Z]\{1,\}[^\.]")"
	    if [ "$GBra" ]; then
		if [ "$GBra" == "master" ]; then
		    local GBra="Master"			# Because why waste space
		fi
	    else
		local GBra="ERROR"			# It could happen supposedly?
	    fi
	    ### End Branch ### }}}

	    GITSTATUSPROMPT=" ${GitCol}[$GBra]\[${DC}\]"	# Add result to prompt
	    
	    ### Find Commit Status ### {{{
	    ## Test Modified and Untracked for "0"
	    #
	    # local GDel="$(echo ${GStat} | tr ':' '\n' | grep -c "^[ MARC]D")"

	    local GAhe="$(echo ${GStat} | tr ':' '\n' | grep "^##" | grep -o "ahead [0-9]\{1,\}" | grep -o "[0-9]\{1,\}")"
	    if [ "$GAhe" ]; then
		GITSTATUSPROMPT="\[${GREEN}\]↑\[${DC}\]${GAhe}"	# Ahead
	    fi

	    ## Needs a `git fetch`
	    local GBeh="$(echo ${GStat} | tr ':' '\n' | grep "^##" | grep -o "behind [0-9]\{1,\}" | grep -o "[0-9]\{1,\}")"
	    if [ "$GBeh" ]; then
		GITSTATUSPROMPT+="\[${RED}\]↓\[${DC}\]${GBeh}"	# Behind
	    fi
	    
	    local GMod="$(echo ${GStat} | tr ':' '\n' | grep -c "^[ MARC]M")"
	    if [ "$GMod" -gt "0" ]; then
		GITSTATUSPROMPT+="\[${MAGENTA}\]≠\[${DC}\]${GMod}"	# Modified
	    fi

	    local GUnt="$(echo ${GStat} | tr ':' '\n' | grep -c "^\?")"
	    if [ "$GUnt" -gt "0" ]; then
		GITSTATUSPROMPT+="\[${YELLOW}\]?\[${DC}\]${GUnt}"	# Untracked
	    fi
	    ### End Commit Status ### }}}
	fi
    else
	MISSING_ITEMS+="git-prompt, "
    fi
    echo -ne "${GITSTATUSPROMPT} "
    ### End Git Status ### }}}
}


last_command () {

    if [ ${MODE} = full ]; then
	CMDNUMB="\! \# "
    else
	CMDNUMB=""
    fi 

    # Last Command Success
    if [ ${EXITSTATUS} = 0 ]; then
	#smiley
	FACE=$'\u263a'
	if [ "$color_prompt" = yes ]; then
            SMILE="\[${GREEN}\]${FACE} ${CMDNUMB}\[${DC}\]"
	else
         SMILE=":) ${CMDNUMB}"
	fi
    else 
	#frowney
	FACE=$'\u2639'
	EXITSTATUS="${EXITSTATUS} "
	if [ "$color_prompt" = yes ]; then
         SMILE="\[${BRED}\]${FACE} ${EXITSTATUS}${CMDNUMB}\[${DC}\]"
	else
        SMILE=":( ${EXITSTATUS}${CMDNUMB}"
	fi
    fi
    echo -en "${SMILE}"
}



host_color () {

    # Only Display Host info if remote login
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	if [ "$color_prompt" = yes ]; then
            HOSTTEXT="@\[${HC}\]\h \[${DC}\]"
	else
            HOSTTEXT="@\h "
	fi
    fi
    echo -en $HOSTTEXT
}


function __svn_prompt () {
echo -en "SVN"
#REV=$(svn info 2>/dev/null | grep Revision | sed -e 's/Revision: //')
    #[ "$REV" ] || return
    #[ "$(svn st)" ] && DIRTY=' *'
    
    #subversion2
    #parse_svn_branch() { 
    #parse_svn_url | sed -e ’s#^’“$(parse_svn_repository_root)”‘##g’ | awk ‘{print “ (svn::”$1")“ }’ 
    #}
    #parse_svn_url() { 
    #svn info 2>/dev/null | sed -ne ’s#^URL: ##p' 
    #}
    #parse_svn_repository_root() { 
    #svn info 2>/dev/null | sed -ne ’s#^Repository Root: ##p' 
    #
}

__screen () {
# SRCEEN
    if [[ $TERM =~ screen ]] ; then
	SCREEN="${BCYAN}(SCREEN)\[${DC}\] "
    else
	SCREEN=""
    fi
    echo -ne ${SCREEN}
}

__debian_chroot () {
    # set variable identifying the chroot you work in 
    # (used in the prompt below)
    if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(cat /etc/debian_chroot)
	echo -ne "\[${DC}\][ ${debian_chroot:+($debian_chroot)} ]\n"
    fi
}

loadprompt $@
