#!/bin/bash

function getgpgkey () {
    local keyVal
    keyVal=$(gpg -K |
                 grep -v expired |
                 grep -v revoked |
                 awk '/sec/{if (length($2) > 0) print $2}' |
                 sed 's|.*/0x||' )
    echo -ne "${keyVal}"
}

function getsshkey () {
    local sshKeys
    local Keys

    cd "${HOME}/.ssh/" &&
        sshKeys=$(ls *.pub |
                      cut -d. -f1 |
                      cut -d- -f1 |
                      cut -d_ -f2 |
                      sort -u) &&
        cd "${HOME}" || return

    for key in ${sshKeys}
    do
        if [[ "${key}" != "gpg" ]]; then
            if [[ -f ${HOME}/.ssh/id_${key} ]]; then
                if [[ -z ${Keys} ]]; then
                    Keys="id_${key}"
                else
                    Keys="${Keys} id_${key}"
                fi
            fi
        fi
    done
    echo -ne "${Keys}"
}

function start_gpg_agent () {
    local gpg_keys=$1
    if command -v keychain > /dev/null 2>&1; then
        if [[ ${TERM} =~ screen ]]; then
            eval "$(keychain --quick --eval --agents gpg ${gpg_keys})"
        else
            eval "$(keychain --clear --systemd --eval --agents gpg ${gpg_keys})"
        fi
    fi
}

function start_desktop_ssh_agent () {
    local sshKeys=$1
    if command -v keychain > /dev/null 2>&1; then
        eval "$(keychain --quick --eval --agents ssh ${sshKeys})"
    fi
}

function start_cli_ssh_agent () {
    local ssh_keys=$1
    if command -v keychain > /dev/null 2>&1; then
        if [[ ${TERM} =~ screen ]]; then
            eval "$(keychain --quick --eval --agents ssh ${ssh_keys})"
        else
            eval "$(keychain --clear --eval --agents ssh ${ssh_keys})"
        fi
    fi
}

function cli_agents () {
    local gpg_keys
    local ssh_keys

    gpg_keys=$(getgpgkey)
    ssh_keys=$(getsshkey)

    if [[ -n "${gpg_keys}" ]]; then
       start_gpg_agent $"{gpg_key}"
    fi

    if [[ -n "${ssh_keys}" ]]; then
        start_cli_ssh_agent "${ssh_keys}"
    elif [[ -n "${gpg_keys}" ]]; then
        config_gpg_ssh_agent
    fi
}

function config_gpg_ssh_agent () {
    unset SSH_AGENT_PID
    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
        export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
    fi
    export GPG_TTY=$(tty)
    gpg-connect-agent updatestartuptty /bye >/dev/null

}

function desktop_agents () {
    # #export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"
    # #export SSH_AGENT_PID="$(ps -e|grep gcr | cut -d\  -f3)"
    local gpg_keys
    local ssh_keys

    gpg_keys=$(getgpgkey)
    ssh_keys=$(getsshkey)

    if [[ -n "${gpg_keys}" ]]; then
       start_gpg_agent "${gpg_keys}"
    fi

    if [[ -n "${ssh_keys}" ]]; then
        start_desktop_ssh_agent "${ssh_keys}"
    elif [[ -n "${gpg_keys}" ]]; then
        config_gpg_ssh_agent
    fi

}

function start_agents () {
    if [ -n "$DESKTOP_SESSION" ]; then
        desktop_agents
    else
        cli_agents
    fi
}

start_agents
